site_name: MiniTorch
site_description: A miniature PyTorch-style deep-learning engine built from scratch
site_author: Samit Mohan
site_url: https://samitmohan.github.io/minitorch/

repo_url: https://github.com/samitmohan/minitorch
repo_name: samitmohan/minitorch 
edit_uri: edit/master/docs 

nav:
  - Home: index.md
  - Getting Started:
      - Quickstart: quickstart.md
      - MNIST Tutorial: mnist.md
  - Tutorial: tutorial.md
  - API Reference:
      - Tensor: api/tensor.md
      - Layers: api/layers.md
      - Loss Functions: api/loss.md 
      - Elementwise: api/elementwise.md
      - Optimizers: api/optim.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: lime
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: lime
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
        
  font:
    text: Roboto
    code: Roboto Mono
    
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.path
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate
    - search.share 
    
  icon:
    repo: fontawesome/brands/github
    
  favicon: assets/favicon.ico

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - md_in_html
  - toc:
      permalink: "¤"
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      pygments_lang_class: true
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/samitmohan
  generator: false  

copyright: |
  &copy; 2024 <a href="https://github.com/samitmohan" target="_blank" rel="noopener">Samit Mohan</a>