site_name: MiniTorch
site_description: A miniature PyTorch-style deep-learning engine built from scratch
site_author: Samit Mohan
site_url: https://samitmohan.github.io/minitorch/  

repo_url: https://github.com/samitmohan/minitorch
repo_name: GitHub
edit_uri: edit/main/docs
nav:
  - Home: index.md
  - Tutorial & Use Cases:
      - Tutorial: tutorial.md
  - API:
      - Tensor: api/tensor.md
      - Layers: api/layers.md
      - Losses: api/loss.md
      - Optimizers: api/optim.md

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode  
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
  language: en
  favicon: assets/favicon.ico 

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed